feat(xml): The more robust and clearer two-pass parser
tableauio/tableau pull request #9
Opened 2022-06-08 07:38 UTC by huieric

The xml parser was refactored into a two-pass parser:
1. Read xml file with `xmlquery`, construct a recursively self-described tree structure defined in `xml.proto` and put it into memory.
2. Preprocess the tree structure. In this phase the parser will do some necessary jobs before generating a 2-dimensional sheet, like `correctType` which make the types of attributes in the nodes meet the requirements of `protogen`.
3. Transform the recursive tree structure into a 2-dimensional sheet, which can be further processed into `protoconf`.

2022-06-10 08:52 UTC, wenchy requested changes

2022-06-13 06:39 UTC, huieric commented on test/dev/proto/feature_toggle_conf.proto
> +      google.protobuf.Timestamp close_time = 5 [(tableau.field) = {name:"CloseTime" prop:{default:"2022-01-23 15:40:00"}}];
done

2022-06-13 07:47 UTC, huieric commented on proto/tableau/protobuf/xml.proto
> +}
done

2022-06-13 07:47 UTC, huieric commented on proto/tableau/protobuf/xml.proto
> +message XMLMeta {
done

2022-06-13 07:47 UTC, huieric commented on proto/tableau/protobuf/xml.proto
> +message Node {
done

2022-06-17 09:39 UTC, huieric commented on internal/importer/xml.go
> +func correctType(xmlSheet *tableaupb.XMLSheet, curr *tableaupb.Node, oriType string) (t string) {
done

2022-06-17 11:12 UTC, wenchy approved these changes

2022-06-17 11:13 UTC, merged