feat(confgen): auto detect map unique
tableauio/tableau pull request #96
Opened 2024-05-13 12:20 UTC by Kybxd

close #78

2024-05-13 15:03 UTC, wenchy requested changes

2024-05-13 15:03 UTC, wenchy commented on internal/localizer/i18n/config/ecode/zh.yaml
> +  help: 请确保map中最多仅有一个key为空, 如果确实需要map中多个key为零值请手动填充零值
change to:
```
  desc: map contains multiple empty keys
  text: map "{{.Name}}" 多个空值key
  help: 请确保map中最多仅有一个空值key，如果确实需要多个key为零值，请显式填充。
```

2024-05-13 15:09 UTC, Kybxd commented on internal/localizer/i18n/config/ecode/en.yaml
> +  help: ensure there is only one empty or key in map, if you need multiple zero-value keys you should explicitly assign a zero value
done

2024-05-13 15:09 UTC, Kybxd commented on internal/localizer/i18n/config/ecode/zh.yaml
> +  help: 请确保map中最多仅有一个key为空, 如果确实需要map中多个key为零值请手动填充零值
done

2024-05-14 03:36 UTC, wenchy requested changes

2024-05-14 03:36 UTC, wenchy commented on xerrors/ecode.go
> +	return renderEcode("E2017", nil)
Need variable `Name` to be injected.

2024-05-14 06:26 UTC, Kybxd commented on xerrors/ecode.go
> +	return renderEcode("E2017", nil)
done

2024-05-14 06:28 UTC, wenchy requested changes

2024-05-14 06:28 UTC, wenchy commented on xerrors/ecode.go
> +// E2017: map value present while key not present.
change to : `// E2017: map contains multiple empty keys.`

2024-05-14 06:48 UTC, wenchy requested changes

2024-05-14 06:48 UTC, wenchy commented on internal/confgen/parser.go
> +					return false, xerrors.WithMessageKV(xerrors.E2017(keyColName), kvs...)
Use `field.fd.FullName()` and `field.fd.Kind().String()` to fill E2017 error info.

2024-05-14 13:33 UTC, wenchy approved these changes
LGTM

2024-05-14 13:34 UTC, merged